# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PDFgoQuery' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PDFgoQuery
  pod 'AFNetworking'
  pod 'YTKNetwork'
  pod 'Masonry'
  pod 'IQKeyboardManager'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'SDWebImage'
  pod 'Toast'
  pod 'ReactiveObjC'
  pod 'YBImageBrowser'
  pod 'WMPageController', '~> 2.4.0'
  # pod 'Realm'
  


end
